language: ruby

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - rake db:create
  - rake db:migrate
  - rake load_csv[data.csv]

branches:
    only:
        - master

script:
  - git branch
  - bundle exec rake

bundler_args: "--without development"
cache:
  - bundler

notifications:
  email: false
