default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 192.168.99.100
  port: 32768
  user: rails

development:
  <<: *default
  database: gi_bill_comparison_tool_development

test:
  adapter: postgresql
  database: travis_ci_test
  host: 192.168.99.100
  port: 32768
  user: rails

production:
  <<: *default
  database: gi_bill_comparison_tool_production
