default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gi_bill_comparison_tool_development

test:
  adapter: postgresql
  database: travis_ci_test

production:
  <<: *default
  database: gi_bill_comparison_tool_production
